### PR TITLE
Export to SVG/PDF

### PR DESCRIPTION
**Pull request by ikajic**
Opening this PR to notify folks I'm working on #10 . Still work in progress!

Exporting to SVG works but the XML ignores CSS so the exported images look crappy, working on embedding CSS properly.

### CODE REVIEW

**Comment by ikajic** [comment]
Embedded CSS into the SVG file but only browsers can read the CSS (opening the .svg image in any other viewer will give rubbish). What works now is opening the .svg in browser and printing as .pdf

**Comment by ikajic** [comment]
Ready to be tested! 

Some of the issues I have encountered:
- Print svg as pdf in browser does not work for `Chromium 45.0.2454.85 Built on 8.1, running on Debian 8.2`
- Save button doesn't do anything with `Mozilla Iceweasel 38.2.1` (working on this), but hey at least it prints it nicely as a pdf :)

**Comment by tbekolay** [comment]
This is awesome!! It will save a ton of time making figures in the future! Even if these aren't perfect, they should definitely be in 0.2 as tweaking an existing SVG is way easier than making one from scratch. This worked well on my machine, which is running Mac OS X and Chrome version 49.0.2623.28.

I noticed a few minor issues trying this out:

1. I think the export layout button should be to the left of the settings icon -- I think it's just natural for the settings to be on the far right.
2. I would expect pressing the "save" button the modal dialog window to close the modal dialog. I opened the SVG right after saving it, and was surprised to see the modal dialog still up when I came back to that tab.
3. The font in the SVG was incorrect for me; `nengo_gui` uses `font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif`, but I get no font-family in the saved SVG, which renders for me as Times New Roman. Definitely not a dealbreaker, but something to maybe make into an issue to deal with later?
4. I noticed in the saved SVG that there are two `<defs xmlns...><style type="text/css"><![CDATA[...` tags. They look to have identical content. Looking at it in `nengo_gui` itself, this appears to actually be a problem there too, so it isn't a bug in the SVG serialization itself.

A more long-term thing related to 1. is that our toolbar is getting pretty long at the top. Most modern interfaces have opted for a button that expands into a dropdown with the things that you want quick-but-not-immediate access to (e.g., the hamburger at the top right of Chrome). A long toolbar can be a bit overwhelming for a user. So, I made issue #666 to keep that work separate from this PR.

**Comment by ikajic** [comment]
> The font in the SVG was incorrect for me; nengo_gui uses font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif, but I get no font-family in the saved SVG, which renders for me as Times New Roman. Definitely not a dealbreaker, but something to maybe make into an issue to deal with later?

Are you fine with me changing stuff in `netgraph.css`? Following seems to work:
```css
.netgraph {
    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
}
```

**Comment by tbekolay** [comment]
Seems fine to me! I think the style is currently applied by Bootstrap, so including it in our CSS should only be a good thing.

**Comment by ikajic** [comment]
> I noticed in the saved SVG that there are two <defs xmlns...><style type="text/css"><![CDATA[... tags. They look to have identical content. Looking at it in nengo_gui itself, this appears to actually be a problem there too, so it isn't a bug in the SVG serialization itself.

I don't have a rational explanation of what happened here. I managed to reproduce this once and every other time I saved SVG it had just one tag... do you mind trying again to see if you can reproduce it?

**Comment by tbekolay** [comment]
The new changes fix 1-3 for me! And I figured out how to reproduce 4: it happens if I export the SVG multiple times; it adds a `defs` tag for each time I export. So, a few possible ways to fix it: 1) add the defs tag when the root SVG is created (rather than when it's exported), 2) delete the defs tag once the SVG is exported, or 3) detect if a defs tag exists and only add it if it isn't there.

**Comment by ikajic** [comment]
> And I figured out how to reproduce 4: it happens if I export the SVG multiple times; it adds a defs tag for each time I export.

Aah.. thanks for figuring this out!

>  1) add the defs tag when the root SVG is created (rather than when it's exported)

This seems to be the cleanest solution! I assume [this](https://github.com/nengo/nengo_gui/blob/master/nengo_gui/static/modal.js#L404) is where the SVG object gets created?

**Comment by tbekolay** [comment]
I think it's [this one](https://github.com/nengo/nengo_gui/blob/master/nengo_gui/static/components/netgraph.js#L115)

**Comment by jgosmann** [comment]
Cool stuff. It seems that ImageMagick is able to convert the SVG including the CSS to other formats. But it produces shitty results for me (e.g., circles get polygons). Maybe that can be fixed with appropriate arguments to `convert`, but maybe not.

> 1) add the defs tag when the root SVG is created (rather than when it's exported)

This would technically still leave the CSS in there twice (from the `<link>` tag and in the SVG). It might be better to get rid of the linked CSS and have it only defined in the SVG. We probably can pass the CSS content from Python to the JS-Netgraph constructor.

**Comment by ikajic** [comment]
> Cool stuff. It seems that ImageMagick is able to convert the SVG including the CSS to other formats. But it produces shitty results for me (e.g., circles get polygons). Maybe that can be fixed with appropriate arguments to convert, but maybe not.

I have tried several packages (including convert) for SVG to PDF conversion but it is actually not an easy problem. Usually they would export just pieces of an image which they are programmed to recognize. Until further, the solution to getting a PDF really is to do print from a browser.

> 1) add the defs tag when the root SVG is created (rather than when it's exported)
> This would technically still leave the CSS in there twice (from the <link> tag and in the SVG). It might be better to get rid of the linked CSS and have it only defined in the SVG. We probably can pass the CSS content from Python to the JS-Netgraph constructor.

I don't see a `<link>` tag in the exported SVG, did you mean having a `<link>` in `page.html`? Also what do you mean by "pass the CSS content from Python to the JS-Netgraph constructor"?

**Comment by jgosmann** [comment]
> did you mean having a <link...> in page.html?

yes

> what do you mean by "pass the CSS content from Python to the JS-Netgraph constructor"?

The JS code line invoking the constructor of the Netgraph class gets put together by the Python backend and is inserted into `page.html` at the appropriate place before sending it to the browser. So it would be possible to read the CSS file with Python and insert it into the constructor call generated with Python.

**Comment by jgosmann** [comment]
[Could this help?](https://github.com/shakiba/svgexport)

**Comment by ikajic** [comment]
>
> Could this help? <https://github.com/shakiba/svgexport>
>

Not really. The results with SVG->PNG->PDF were crappy. I would leave the
scope of this PR to focus on exporting the layout to SVG and in the future
address the conversion to PDF. I will rename the  branch to reflect that.

So it would be possible to read the CSS file with Python and insert it into
> the constructor call generated with Python.
>
Why would we want to do that?

**Comment by jgosmann** [comment]
> I would leave the scope of this PR to focus on exporting the layout to SVG and in the future address the conversion to PDF.

Yeah, I never meant to imply, that this should be part of this PR.

> Why would we want to do that?

To only have one place that defines the CSS (e.g., to avoid confusion when debugging).

**Comment by tcstewar** [comment]
This looks good to me, other than a block of code in ```modal.js``` where the only change is some spacing, due to some commits that removed and then replaced that code.  @tbekolay , my feeling is if that's fixed and then we maybe squash some commits together, this should be all set.  Does that make sense to you?  And perhaps the squashing would resolve the merge conflicts...

**Comment by tbekolay** [comment]
Yes, I would definitely remove the spacing change and squash the commits. Dunno if it'll resolve the conflicts altogether, but it should be easier to deal with! LMK if you want me to handle the rebase.

**Comment by tcstewar** [comment]
> Yes, I would definitely remove the spacing change and squash the commits. Dunno if it'll resolve the conflicts altogether, but it should be easier to deal with! LMK if you want me to handle the rebase.

If you could take a stab at that, that'd be great.  :)  Thank you!

**Comment by tbekolay** [comment]
OK, rebased and squashed. I haven't tested it in the squashed state though, so would be good to re-test before merging.

**Comment by tcstewar** [comment]
> OK, rebased and squashed. I haven't tested it in the squashed state though, so would be good to re-test before merging.

Thanks!  I'll do that now....

**Comment by tcstewar** [comment]
Functions great for me, other than a small typo while merging.  I'll wait for the tests to complete and then merge.  Thank you for the rebasing/squashing!

**Pull request merged**
