### PR TITLE
Immobile sim times

### PR DESCRIPTION
**Pull request by cchan987**
Prevents times from racing across the sim_control bar.

### CODE REVIEW

**Comment by cchan987** [comment]
addresses #3

**Comment by cchan987** [comment]
should we cut the time: XX:xx field from the sim control's metric container?

**Comment by tbekolay** [comment]
I was curious what this looked like, so I rebased it to master. Here it is!

screen shot 2015-06-09 at 3 52 52 pm

I think with some tweaks this could be an improvement. I'm not sure where the numbers should be, but they look odd where they are.

Also, it would be super helpful if this also showed the times at the left and right of what is actually being shown (depending on the blue window).

**Comment by tbekolay** [comment]
Oh, and also, a bit of bug: if you resize the window, the numbers don't move, and therefore disappear. Probably something needs to be added to the function called on resize.

**Comment by Seanny123** [comment]
@tbekolay what if the number were overlayed on top of the line like so:
better bar

**Comment by Seanny123** [comment]
On hold until #534 is resolved.

**Comment by tcstewar** [comment]
This PR is rather out of date, and the current display seems to be working well, so I'm closing this one.

**Pull request closed without merging**
