### PR TITLE
Hbb tutorials

### PR DESCRIPTION
**Pull request by s72sue**
Added the tutorials from 'How to Build a Brain' book so that its easier for people following the book to run them in nengo_gui (instead of running them in iPython notebooks).

### CODE REVIEW

**Comment by s72sue** [comment]
@celiasmith : do you mind taking a look?

**Comment by celiasmith** [comment]
I made several minor changes above.  The one major thing is that the chapter 5 and 7 tutorials don't have any graphs by default.  @s72sue could you add those to the .cfg files?

**Comment by s72sue** [comment]
Chapter 5 and 7 tutorials had graphs in the last commit I made (869cdb3). I think the reason the graphs are not showing up is because you numbered the simulations, and so the config files do not have the same names anymore. I will rename the config files to match the simulation names so that the config files can be loaded appropriately.

**Comment by celiasmith** [comment]
ah, haha... i broke it!  sorry about that 😄   i'll finish taking a look now.

**Comment by celiasmith** [comment]
@tcstewar did you want to do the merge to master?

**Comment by tcstewar** [comment]
> @tcstewar did you want to do the merge to master?

Nice!  Great to have these rewritten!  I'll go the merge.....

**Comment by tcstewar** [comment]
It looks like the file nengo_gui/examples/tutorial/01-one-neuron.py.cfg was also changed.  Was this on purpose, or should I remove it from this PR?

**Comment by s72sue** [comment]
Oh sorry, I didn't intend to change it.

**Comment by celiasmith** [comment]
@tcstewar I  just rebased this to master, hopefully to avoid the missing .jar on travis.

**Comment by tcstewar** [comment]
All merged!  Thank you for putting this together!

**Pull request merged**
