### PR TITLE
Fix label svg sizing

### PR DESCRIPTION
**Pull request by Seanny123**
Current method doesn't work for long labels, because I forgot to include the text as part of the label class...

### CODE REVIEW

**Comment by tcstewar** [comment]
What can I do to see the incorrect behaviour that this is trying to fix?  I've mucked with making long labels, and it seems to work for the things I've tried (mostly opening a SPA plot and a SPA cloud and seeing what happens when I create new semantic pointer inputs with long or short text names).

**Comment by Seanny123** [comment]
You'd only see it on the other branches and on reload of a network with a saved config including long labels.

**Comment by tcstewar** [comment]
So this only affects things that can't happen on the master branch?  Hmm, that does make it hard/impossible to test, but it is a pretty small change, so I guess it's okay.  Technically it should be done in those other branches, but whatever.  :)

**Comment by tcstewar** [comment]
Again, if  you fix the conflicts, I can merge...  :)

**Comment by tcstewar** [comment]
Btw, what method are you using to update the branch to master to fix these conflicts?

**Pull request merged**
