### PR TITLE
Fix editor scrolling problem (#499)

### PR DESCRIPTION
**Pull request by tcstewar**
I believe this will fix the scrolling problem encountered in Chrome 44 (See issue #499)

If people could test it out on their browsers, that would be great!

### CODE REVIEW

**Comment by jgosmann** [comment]
Assigned this to myself because I want to give this a test before it's merged (but might not be able to test it right away as I am on a limited WIFI connection right now). I have a feeling this change might break other things related to some layout changes I introduced.

**Comment by jgosmann** [comment]
Ok, tested it out and doesn't seem to break anything and fixes the problem in Chrome 44 on OS X for me.

**Comment by tcstewar** [comment]
> Ok, tested it out and doesn't seem to break anything and fixes the problem in Chrome 44 on OS X for me.

Yay!  I was hoping you'd take a look as you've got more experience with the flex layout stuff than anyone else.  :)

**Comment by tcstewar** [comment]
Argh, I just tested this under Chrome 43 and it works great....  except that if you toggle the editor window off and then on the editor window does not reappear.  :(

**Comment by tcstewar** [comment]
And it's also the case that on Firefox this PR means that if you toggle the editor off and then on again, it doesn't reappear.  :( :(  Any suggestions for fixing that?  I'll start trying stuff at random again...  :)

**Comment by jgosmann** [comment]
Interesting, I didn't expect that behavior ...

**Comment by jgosmann** [comment]
I think, the issue is simply that the `display` property of `#rightpane` gets set to `block` instead of flex if the editor is toggled.

**Comment by tcstewar** [comment]
> I think, the issue is simply that the display property of #rightpane gets set to block instead of flex if the editor is toggled.

Good catch!  Yup, that seems to fix it.  :)  Working fine on Firefox and Chrome 43 right now (the two browsers I have access to at the moment).  Does that fix it for you?

**Comment by jgosmann** [comment]
Now the console doesn't appear anymore in case of a syntax error.

**Comment by tcstewar** [comment]
> Now the console doesn't appear anymore in case of a syntax error.

???  Weird...  it does for me in Firefox and Chrome 43....  grr....

**Comment by jgosmann** [comment]
Just wanted to look into this, but now it does work for me? :confused: 
No idea what was going on ...

**Comment by tcstewar** [comment]
> Just wanted to look into this, but now it does work for me?  
> No idea what was going on ..

Curiouser and curiouser.....  I'll try it on a bunch of browsers at the office tomorrow and if it still seems to work we'll merge and deal with the consequences when they come up...  :)

**Comment by tcstewar** [comment]
I've had enough people indicate that it works for them that I'm going to go ahead and merge this.  :)

**Pull request merged**
