### PR TITLE
Click on file name to save-as

### PR DESCRIPTION
**Pull request by tcstewar**
Here's a first version of save-as.  The current functionality is tied to clicking on the file name, which I don't particularly like, but seems okay for now until we rethink the top toolbar.

If you try to rename to an existing filename, it will give an error message.  If you try to rename to an invalid file name, it will also give an error message.

### CODE REVIEW

**Comment by rsimmons1** [comment]
LGTM, is it tested on windows and OSX? any ideas for selenium testing?

**Comment by rsimmons1** [comment]
If the name of the file highlighted as the mouse scrolls over the file name it would be much clearer that it is a button.

**Comment by rsimmons1** [comment]
Now tested on linux, windows and OSX works great on all 3, including error messages.

**Comment by rsimmons1** [comment]
Created python test for the save as functionality, its pretty generalized, the test should work even if we have to tweak this functionality.

**Comment by tcstewar** [comment]
> It would be much clearer that it is a button if the name of the file highlighted as the mouse scrolls over it. Like the other buttons in the top bar

Good idea!  That's now added.  :)

**Pull request merged**
