### PR TITLE
Enable console text selection

### LINKED ISSUE #634: Text in console is not selectable.
This makes it hard to copy and paste errors.

### PR DESCRIPTION
**Pull request by s72sue**
Fixes #634

### CODE REVIEW

**Comment by jgosmann** [comment]
You should change all of the `*-select` lines. Also, this exacty reverts 85c8e31c7ade5deb237e1d644cb4a544919fa439. We probably should decide whether we want to
1. allow text selection in general
2. disallow text selection in general
3. only allow text selection in certain areas (like the console)

**Comment by s72sue** [comment]
Hmm...I didn't know about this other issue. I think it would make sense to
allow text selection in certain areas like the console. We definitely don't
want text getting randomly selected in the visualizer since that can be
confusing (and looks weird).

**Comment by s72sue** [comment]
I have made the change to enable text selection in console while disabling accidental selection in the visualizer. 

jgosmann This seemed to be the most sensible combination to me, but let me know if people want some other combination for allowing/disallowing text selection in certain areas.

**Comment by tcstewar** [comment]
Looks good to me.  :)

That said, watch out for including extra files into the PR that aren't part of it.  They greatly complicate the review process and mean that when we look back in the history to find out why certain lines were added, we get a lot of extraneous information to sift through.

**Comment by s72sue** [comment]
Oh I apologize ..didn't realise that those files got added to the PR. Will
definitely watch out in the future.

**Pull request merged**
