### PR TITLE
Shaded borders

### PR DESCRIPTION
**Pull request by tcstewar**
Here's a third version of the ongoing fun with resizing.

Here, instead of having borders, the item gets a faint shading applied to it.  This is a lot more subtle, but still draws attention and gives you a sense of where the object boundary is for the resizing.

### CODE REVIEW

**Comment by jgosmann** [comment]
If the frames didn't look like a debug version, this definitely does!

A bit different styling might help ... but not sure ...

**Comment by tcstewar** [comment]
> If the frames didn't look like a debug version, this definitely does!

This is why I'm trying lots of different possibilities...   this looks less debuggy to me, but I'm weird. :)

**Comment by celiasmith** [comment]
This works well on the networks (except it flashes when you drag over connections, as did the outlining... but that's ignorable for now).  But, i agree it looks weird on nodes and ensembles.  Making it a circle around ensembles and a rounded rectangle on nodes, unfortunately won't help the issue.  Sorry, I don't have anything more constructive :disappointed:

**Comment by tbekolay** [comment]
Initially I actually thought that it was just the fill color of the node rectangle or ensemble circles changing, which I kind of liked (and would work with highlighting the right line in the source code editor) but yeah, having it be a full rectangle looks weird/debuggy to me, especially within expanded networks. I think if we have intuitive resizing behavior, we won't need to have this kind of visual help...

**Comment by tcstewar** [comment]
People seem happy without any visual indication for now, and if we want to implement it it'll be easier to do it from scratch than to use this PR.

**Pull request closed without merging**
