### PR TITLE
disconnection warning with modal

### PR DESCRIPTION
**Pull request by cchan987**
When the simcontrol websocket closes, warning modal is displayed.

User is prompted to restart server and refresh page 

In regards to #349

### CODE REVIEW

**Comment by tcstewar** [comment]
seems pretty solid to me, but I think the error message itself needs some tweaking.  Right now it says 

```
Server Communication Error
Please ensure that the GUI server is running then refresh page
```

How about something like this:

```
Nengo has stopped running
To continue working with your model, re-run nengo_gui and click Refresh.
```

**Comment by tcstewar** [comment]
looks good...  merging...

**Comment by jgosmann** [comment]
I think, the red background looks too aggressive. Maybe we could do something more unobstrusive like "connection lost" text in the toolbar (which can have a lighter red background)?

**Comment by tcstewar** [comment]
I could also see just getting rid of the colour change...  the modal does a pretty good job on its own.

**Comment by jgosmann** [comment]
Yeah, that would also be fine. Though, some form of indication can help to figure out wether the server corresponding to a realy old tab (where I might have closed the modal) is still running.

**Comment by tcstewar** [comment]
> Though, some form of indication can help to figure out wether the server corresponding to a realy old tab (where I might have closed the modal) is still running.

Maybe have it show a message in the console?

**Comment by jgosmann** [comment]
I like the Jupyter way with the red connection message and that broken link symbol to the right (which gives you a tooltip explaining the meaning:
snapshot2

**Comment by tcstewar** [comment]
Since this PR has closed, I've started a new issue to track this discussion.  :)  #492

**Pull request merged**
