### PR TITLE
Spa similarity plot

### PR DESCRIPTION
**Pull request by Seanny123**
Created a spa similarity plot which tracks the similarity of a SPA pointer over time in a value-like plot, which resulted in a lot of little changes:
- Creation of VariableDataStore for graphs whose lines grow over time
- Creation of pure-JavaScript unit tests for DataStore and VariableDataStore
- First draft of a legends-like object, but so far only for the similarity graph

To test the file use the following code
```
import nengo
import nengo.spa as spa

D = 16

vo = spa.Vocabulary(D)
vo.parse("SHIRT+PANTS+SHOES+SOCKS")

model = spa.SPA()
with model:
    model.display = spa.Buffer(D, vocab=vo)
    model.input_buf = spa.Buffer(D, vocab=vo)

    nengo.Connection(model.input_buf.state.output, model.display.state.input)
```

### CODE REVIEW

**Comment by cchan987** [comment]
Does this require installation of a module ipdb?

**Comment by Seanny123** [comment]
Yeah. I use that for debugging.

**Comment by s72sue** [comment]
@Seanny123 I am on this branch trying to get the similarity plots for my example. However I don't see any spa-similarity-plot option in the right-click menu. Is there some other way to get these plots?

**Comment by Seanny123** [comment]
There should be a semantic-pointer-graph option

**Comment by s72sue** [comment]
I am a bit confused. Semantic pointer graphs were there before as well, and they used to show the vectors based on similarity. However, I thought this was about generating similarity plots over time and I don't see them (I still see the old semantic pointer plots). I am wondering what I am missing here?

**Comment by Seanny123** [comment]
Current issues with this branch:
- does not work with the built-in spa.py example
- does not work if one changes the number of pointers in the vocabulary by typing a novel pointer

**Comment by Seanny123** [comment]
@tcstewar This pull request is ready for your review. Obviously I'm going to squash the commits and it still doesn't support "show-pairs", but I would like your opinion on what I've done so far.

**Comment by Seanny123** [comment]
Based off the meeting, a few options for showing the maximum value of the graph need to be considered. First, showing the maximum value as a sub-title under the label. Second, have a dynamic legend showing the top five values in a non-sorted order. Finally, being able to hover over the lines to see what the top values are.

**Comment by Seanny123** [comment]
Change parenthese to equation (add elipsis if too long) , reduce font size,  post screenshot for other opinions.

**Comment by Seanny123** [comment]
Also try averaging and numbers on the side.

**Comment by Seanny123** [comment]
1. Add numbers to legend
2. Dream about cross-hairs and interactivity and merge

**Comment by Seanny123** [comment]
This is an old pull request who's code is out of date, so I'm closing it.

**Comment by tbekolay** [comment]
Guessing these commits got repurposed in another PR that was merged? Can we delete the branch as well?

**Comment by Seanny123** [comment]
Some of the code didn't get repurposed and honestly, I don't know what to do with it. Would it be painful to just leave the branch lying around just in case?

**Comment by tbekolay** [comment]
Yep, no harm in keeping it around!
On Jun 6, 2016 15:41, "Sean Aubin" <notifications@github.com> wrote:

Some of the code didn't get repurposed and honestly, I don't know what to
do with it. Would it be painful to just leave the branch lying around just
in case?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/nengo/nengo_gui/pull/528#issuecomment-224065538>, or mute
the thread
<https://github.com/notifications/unsubscribe/AAMbvU3aBlct1Cg5w4F8QpvFbLalkm6Rks5qJHfqgaJpZM4FpEfs>
.

**Pull request closed without merging**
