### PR TITLE
Fix#703 ensemble resizing

### PR DESCRIPTION
**Pull request by studywolf**
Fix for #703. Just dropping the `this` from the call to `ng`.

### CODE REVIEW

**Comment by tcstewar** [comment]
Just to check, what was your reasoning for the second commit here?  The first commit seems to be the one that fixes the problem....

**Comment by tcstewar** [comment]
> Just to check, what was your reasoning for the second commit here? The first commit seems to be the one that fixes the problem....

Ah, I see, @tbekolay recommended it for consistency.  Cool!

**Comment by tbekolay** [comment]
We discussed it in #703... it's just for consistency, as there was a mix of `ng` and `self.ng` in there.

**Comment by tcstewar** [comment]
Looks good to me...  thanks for finding this....

**Pull request merged**
