### PR TITLE
0.1.5 release

### PR DESCRIPTION
**Pull request by tbekolay**
This PR doesn't have anything in it yet, but I'll update it with a changelog for review soon. Mostly, I'm making this so that people can check it out to make sure there are no major bugs before we go forward with the release.

### CODE REVIEW

**Comment by tcstewar** [comment]
Good idea...  it's been a while since a nengo_gui release, and we may as well have one now before finishing off the stuff for 0.2.  There are a few things sitting in the 0.1.5 milestone still, but I won't have a chance to review them over the next few days, so I think it's okay to move them to 0.2.

**Comment by Seanny123** [comment]
The one issue remaining in the 0.1.5 milestone is important for the tutorial that Su and I made for SPA. If if could be reviewed and included in this release, it would be greatly appreciated.

**Comment by tbekolay** [comment]
I've updated this PR to master, which should contain all of the changes we wanted for 0.1.5. So, anyone who wants to test the proposed 0.1.5 release, please check out this branch so that we can make sure we're all testing with the same code.

I haven't written the changelog yet, but this will need to be done before the release; there have been lots of changes so if anyone feels like writing a brief summary (definitely not a PR-by-PR account like `nengo`'s changelog, just the very brief highlights) then feel free to push it this branch!

**Comment by Seanny123** [comment]
I'll write the changelog.

**Comment by tbekolay** [comment]
sweet, thanks :D What I've done in the past is look at all of the PRs merged since the [last release](https://github.com/nengo/nengo_gui/tree/2f82b66f674402b4822ae58bef63e37ba3342b5e) and write a short bullet point if that change would be interesting to a normal user. Looks like lots of commits since last release, so good luck sir ;)

**Comment by Seanny123** [comment]
Added the entry. Let me know if you want some more detail.

**Comment by tbekolay** [comment]
I think some of the refactoring is user-facing, so it might be worth a brief note about that; e.g., Travis had a script that uses `nengo_gui.GUI`, which I think used to be `nengo_gui.Viz`, so it'd be good to note important renames like that.

Aside from that, has anyone tested with this and had success? @Seanny123, you mentioned in the research blog that you found a nasty bug with 0.1.5?

**Comment by Seanny123** [comment]
I've added to the changelog the deprecation of `Viz` and it's replacement with `GUI`.

The bug I was talking about was #592 . It's nasty in the way that it was super deep, but it wasn't really common.

I'm also working on a dev-facing bug with configuration of components, but my week is looking pretty ridiculous right now, so I think that can wait for 0.2.

**Comment by tbekolay** [comment]
Cool cool. I'll do a bit of smoke testing and release this hopefully this weekend, or worst case Monday morning.

**Comment by tbekolay** [comment]
Went through some of the tutorials as a way of smoke testing, and they worked. The tutorials are also very well done! Will do the release shortly.

**Comment by tbekolay** [comment]
[Released!](https://pypi.python.org/pypi/nengo_gui/0.1.5)

**Comment by tbekolay** [comment]
Oh, as a sidenote, PyPI gave me a 500 error when I uploaded it for some reason. But, I confirmed that 0.1.5 works as expected by making a new virtualenv and pip installing `nengo_gui`.

**Pull request closed without merging**
