### PR TITLE
Add hotkey ctrl-s to save file.

### PR DESCRIPTION
**Pull request by ikajic**
As requested in #757 .

### CODE REVIEW

**Comment by jgosmann** [comment]
Should we add this to the hotkey help dialogue?

**Comment by jgosmann** [comment]
(Apart from that LGTM 🍰 )

**Comment by ikajic** [comment]
> Should  we add this to the hotkey help dialogue?

Done! :sunflower:

**Comment by ikajic** [comment]
I don't get it... why is this failing?

**Comment by jgosmann** [comment]
What is failing?

**Comment by tcstewar** [comment]
Awesome!  thank you so much!

> I don't get it... why is this failing?

what is is failing on?  It seems to work fine for me in Chrome....

**Comment by ikajic** [comment]
Travis CI was complaining about something, but now it looks ok

**Comment by Seanny123** [comment]
LGTM too! Let's merge!

**Pull request merged**
