### PR TITLE
Fix resize

### LINKED ISSUE #422: Ensembles become larger on first resize movment
When resizing an ensemble by dragging an edge, after the first mouse movement the ensemble pops to being a larger size.

### PR DESCRIPTION
**Pull request by jgosmann**
Fixes #422.

Makes some changes to the layout (using flex layout for editor and console) to have the browser handle the size calculations. Hope this doesn't break anything else.

### CODE REVIEW

**Comment by tcstewar** [comment]
I just finally got around to testing this, and it looks good to me, except for one interface weirdness:  This gets rid of the ability to do a corner-resize on the error console (so I can resize both the height and the width of the error console at the same time).  I've found myself using the corner-resize a fair bit....  I'm not quite sure how to get that functionality back in with these changes, though...  thoughts?

**Comment by jgosmann** [comment]
Corner resize works on OS X, but not Linux. :confounded:

**Comment by jgosmann** [comment]
Nevermind, I am too stupid to checkout the correct branch. :unamused:

**Comment by jgosmann** [comment]
Should be fixed now.

**Comment by tcstewar** [comment]
Cool, that fixes the corner resize for me....  :)

However, I just noticed another bug in the flex layout.  It seems to work fin in Firefox (36.0.4) but in Chromium (37.0.2062.94) something seems wrong with the vertical height of the page.  I'm getting a scroll bar on the right-hand side and the placement of the minimap is wrong

image

**Comment by jgosmann** [comment]
Also fixed.

**Comment by tcstewar** [comment]
That's looking good to me now!  :)  thanks!

**Comment by tcstewar** [comment]
Argh, found another bug, after I merged into master.  All the graphs are now on top of the editor.  I let @jgosmann know about it and he's taking a look now.

**Pull request merged**
